### ISSUE TITLE
communicating between Bpod and Bonsai

### ISSUE THREAD

**Issue by chongtianyifa** [sanworks/Bpod_Gen2#14]
Hi Josh,

I have some issues with communicating between Bpod and Bonsai.
1. Previously, I successfully made Bpod listen to Bonsai to trigger state changes. However, I couldn't connect to Bpod to Bonsai using the same code. It seems that the Osc.config file might not be correct anymore since the SendMessage node keeps saying that 'there is an error in xml document (2 2)'.

2. Now I also want to send a message back to Bonsai but have no idea how to make this work. From this thread (https://sanworks.io/forum/showthread.php?tid=3410&highlight=bonsai),  there are two options-either set up a soft code handler or use the dedicated virtual COM port by upgrading to firmware v23. Does the DUE board support one of firmware v23? Can you give me guidance on how to set up the connection on the ends of both Matlab and Bonsai for the two options? 

Thanks,

**Comment by sanworks** [comment]
This issue is fixed in release 1.7.6. This Wiki page should assist with usage:
https://sanworks.github.io/Bpod_Wiki/user-guide/using-bonsai/
