### ISSUE TITLE
SoftCode handling issues

### ISSUE THREAD

**Issue by DaBue93** [sanworks/Bpod_Gen2#15]
Hey guys, 
Since the last update of BPod I still can connect Bonsai with Bpod. However, the softcodes sent by Bonsai do not have the desired effect. It seems that they are no longer recognized. (Nothing is displayed for "last events" in the GUI). Is there already a solution for this?

Cheers,
Daniel

**Comment by sanworks** [comment]
This issue is fixed in release 1.7.6. This Wiki page should assist with usage:
https://sanworks.github.io/Bpod_Wiki/user-guide/using-bonsai/
