### ISSUE TITLE
Downgrading from v23 to v22 and COM Ports not available

### ISSUE THREAD

**Issue by icullen87** [sanworks/Bpod_Gen2#16]
Hello, 
I updated our BPOD v2 to connect to an Analog Module, but when updated to v23, it is no longer compatible with PyBPOD which is what my lab uses. I tried to downgrade it, but now the COM port its connected to is not showing up as an available COM Port. Has anyone else done this successfully?

**Comment by sanworks** [comment]
This was resolved offline, the issue was isolated, and resolved by returning the board's Teensy controller to bootloader mode.
